import { useCallback, useEffect, useState } from 'react';

interface CopyButtonProps {
  content: string;
  modelId: string | null;
}

export function CopyButton({ content, modelId }: CopyButtonProps) {
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState(false);

  useEffect(() => {
    if (copied) {
      const timeoutId = setTimeout(() => setCopied(false), 2000);
      return () => clearTimeout(timeoutId);
    }
  }, [copied]);

  useEffect(() => {
    if (error) {
      const timeoutId = setTimeout(() => setError(false), 3000);
      return () => clearTimeout(timeoutId);
    }
  }, [error]);

  const handleCopy = useCallback(async () => {
    const modelName = modelId ? modelId.split('/').pop() : 'Unknown';
    // LLMが出力する不可視Unicode文字(zero-width space等)と前後の空白を除去
    const cleaned = content.replace(
      /^[\s\u200B-\u200D\u2060\uFEFF]+|[\s\u200B-\u200D\u2060\uFEFF]+$/g,
      '',
    );
    const textToCopy = `${cleaned}\n---\nGenerated by [Briefer](https://github.com/toku345/briefer) (${modelName})`;

    setError(false);

    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
    } catch (err) {
      console.error('[Briefer] Failed to copy:', err);
      setError(true);
    }
  }, [content, modelId]);

  const label = error ? 'コピーに失敗しました' : copied ? 'コピーしました' : 'Markdownをコピー';

  return (
    <button
      type="button"
      className={`copy-button ${copied ? 'copied' : ''} ${error ? 'error' : ''}`}
      onClick={handleCopy}
      title={label}
      aria-label={label}
    >
      {error ? <ErrorIcon /> : copied ? <CheckIcon /> : <CopyIcon />}
    </button>
  );
}

function CopyIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      aria-hidden="true"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      aria-hidden="true"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

function ErrorIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="15" y1="9" x2="9" y2="15" />
      <line x1="9" y1="9" x2="15" y2="15" />
    </svg>
  );
}
