/**
 * @vitest-environment jsdom
 */
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { CopyButton } from '../src/sidepanel/components/CopyButton';

describe('CopyButton', () => {
  const mockWriteText = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
    Object.assign(navigator, {
      clipboard: {
        writeText: mockWriteText,
      },
    });
  });

  it('コピーボタンが表示される', () => {
    render(<CopyButton content="テスト" modelId="meta-llama/test-model" />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    expect(button).not.toBeNull();
  });

  it('クリック時にclipboard APIが呼ばれる', async () => {
    mockWriteText.mockResolvedValueOnce(undefined);

    render(<CopyButton content="テストコンテンツ" modelId="meta-llama/test-model" />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    fireEvent.click(button);

    await waitFor(() => {
      expect(mockWriteText).toHaveBeenCalledWith(
        'テストコンテンツ\n\n---\nGenerated by: test-model',
      );
    });
  });

  it('コピー後にcopiedクラスが追加される', async () => {
    mockWriteText.mockResolvedValueOnce(undefined);

    render(<CopyButton content="テスト" modelId="meta-llama/test-model" />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    fireEvent.click(button);

    await waitFor(() => {
      expect(button.className).toContain('copied');
    });
  });

  it('modelIdがnullの場合「Unknown」が使用される', async () => {
    mockWriteText.mockResolvedValueOnce(undefined);

    render(<CopyButton content="テスト" modelId={null} />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    fireEvent.click(button);

    await waitFor(() => {
      expect(mockWriteText).toHaveBeenCalledWith('テスト\n\n---\nGenerated by: Unknown');
    });
  });

  it('コピーエラー時にコンソールエラーが出力される', async () => {
    const consoleError = vi.spyOn(console, 'error').mockImplementation(() => {});
    mockWriteText.mockRejectedValueOnce(new Error('Copy failed'));

    render(<CopyButton content="テスト" modelId="test-model" />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    fireEvent.click(button);

    await waitFor(() => {
      expect(consoleError).toHaveBeenCalledWith('[Briefer] Failed to copy:', expect.any(Error));
    });

    consoleError.mockRestore();
  });
});
