/**
 * @vitest-environment jsdom
 */
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { CopyButton } from '../src/sidepanel/components/CopyButton';

describe('CopyButton', () => {
  const mockWriteText = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
    Object.assign(navigator, {
      clipboard: {
        writeText: mockWriteText,
      },
    });
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('コピーボタンが表示される', () => {
    render(<CopyButton content="テスト" modelId="meta-llama/test-model" />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    expect(button).not.toBeNull();
  });

  it('クリック時にclipboard APIが呼ばれる', async () => {
    mockWriteText.mockResolvedValueOnce(undefined);

    render(<CopyButton content="テストコンテンツ" modelId="meta-llama/test-model" />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    fireEvent.click(button);

    await waitFor(() => {
      expect(mockWriteText).toHaveBeenCalledWith(
        'テストコンテンツ\n---\nGenerated by [Briefer](https://github.com/toku345/briefer) (test-model)',
      );
    });
  });

  it('コピー後にcopiedクラスが追加される', async () => {
    mockWriteText.mockResolvedValueOnce(undefined);

    render(<CopyButton content="テスト" modelId="meta-llama/test-model" />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    fireEvent.click(button);

    await waitFor(() => {
      expect(button.className).toContain('copied');
    });
  });

  it('modelIdがnullの場合「Unknown」が使用される', async () => {
    mockWriteText.mockResolvedValueOnce(undefined);

    render(<CopyButton content="テスト" modelId={null} />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    fireEvent.click(button);

    await waitFor(() => {
      expect(mockWriteText).toHaveBeenCalledWith(
        'テスト\n---\nGenerated by [Briefer](https://github.com/toku345/briefer) (Unknown)',
      );
    });
  });

  it('コピーエラー時にコンソールエラーが出力される', async () => {
    const consoleError = vi.spyOn(console, 'error').mockImplementation(() => {});
    mockWriteText.mockRejectedValueOnce(new Error('Copy failed'));

    render(<CopyButton content="テスト" modelId="test-model" />);

    const button = screen.getByRole('button', { name: 'Markdownをコピー' });
    fireEvent.click(button);

    await waitFor(() => {
      expect(consoleError).toHaveBeenCalledWith('[Briefer] Failed to copy:', expect.any(Error));
    });

    consoleError.mockRestore();
  });

  it('copied状態が2秒後にリセットされる', async () => {
    vi.useFakeTimers();
    mockWriteText.mockResolvedValueOnce(undefined);

    render(<CopyButton content="テスト" modelId="test-model" />);
    const button = screen.getByRole('button', { name: 'Markdownをコピー' });

    await act(async () => {
      fireEvent.click(button);
    });

    expect(button.className).toContain('copied');

    await act(async () => {
      vi.advanceTimersByTime(2000);
    });

    expect(button.className).not.toContain('copied');
  });

  it('コピーエラー時にerrorクラスが追加される', async () => {
    vi.spyOn(console, 'error').mockImplementation(() => {});
    mockWriteText.mockRejectedValueOnce(new Error('Copy failed'));

    render(<CopyButton content="テスト" modelId="test-model" />);
    const button = screen.getByRole('button', { name: 'Markdownをコピー' });

    fireEvent.click(button);

    await waitFor(() => {
      expect(button.className).toContain('error');
      expect(button.className).not.toContain('copied');
    });
  });

  it('エラー状態が3秒後にリセットされる', async () => {
    vi.useFakeTimers({ shouldAdvanceTime: true });
    vi.spyOn(console, 'error').mockImplementation(() => {});
    mockWriteText.mockRejectedValueOnce(new Error('Copy failed'));

    render(<CopyButton content="テスト" modelId="test-model" />);
    const button = screen.getByRole('button', { name: 'Markdownをコピー' });

    fireEvent.click(button);

    // Promiseが解決するのを待つ
    await act(async () => {
      await Promise.resolve();
    });

    expect(button.className).toContain('error');

    // 3秒進める
    await act(async () => {
      vi.advanceTimersByTime(3000);
    });

    expect(button.className).not.toContain('error');
  });
});
