import { useCallback, useState } from 'react';

interface CopyButtonProps {
  content: string;
  modelId: string | null;
}

export function CopyButton({ content, modelId }: CopyButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    const modelName = modelId ? modelId.split('/').pop() : 'Unknown';
    const textToCopy = `${content}\n\n---\nGenerated by: ${modelName}`;

    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('[Briefer] Failed to copy:', error);
    }
  }, [content, modelId]);

  return (
    <button
      type="button"
      className={`copy-button ${copied ? 'copied' : ''}`}
      onClick={handleCopy}
      title={copied ? 'コピーしました' : 'Markdownをコピー'}
      aria-label={copied ? 'コピーしました' : 'Markdownをコピー'}
    >
      {copied ? <CheckIcon /> : <CopyIcon />}
    </button>
  );
}

function CopyIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      aria-hidden="true"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      aria-hidden="true"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
